# Homework 


   

## Instructor

    Dr. Fatima Boukari
    Division: PEMaCS
    
    


## Problem 1: 

Predict penguins species based on two body measurements: culmen length and culmen depth. 

Q1: Load the data 'penguins_species.csv`

In [3]:
# Write your code here.

Q2: Show the different penguins species in the dataset, the number of samples of each specie? 

- Using Visualization of 2 figures: One bar plot and one pie plot. 

In [4]:
# Write your code here.

Q3: Plot histograms for the numerical features including the kernel

In [5]:
# Write your code here.

Q4: Show features distribution for each class. Hint: use
[`seaborn.pairplot`](https://seaborn.pydata.org/generated/seaborn.pairplot.html)

In [6]:
# Write your code here.

## Problem 2 
In this problem, we apply `LogisticRegression` to predicts 2 different classes: 

class `1` for `' Low'` and 

class `0` for `' High'` 
    
then show the estimated and real classes.

In [20]:
import pandas as pd
import numpy as np

empl = pd.read_csv("Employment.csv")

Q1: Split the dataset to have the output labels separated from the inout features used for training
used to train our predictive model.

In [11]:
# Write your code here.  


Q2: Select the following numerical columns to use for training: `"age"`, `"gains"`, `"losses"` and `"hours-per-week"`

In [14]:
# Write your code here.


Q3: Split the data and output label into a train and test set.

In [15]:
from sklearn.model_selection import train_test_split

# Write your code here.


Q4: Compute the logistic regression model. 

Hint: use `LogisticRegression` method from the scikit-learn and the `linear_model` package then Fit the linear model using the numpy arrays of the features and the labels for the training data set.

In [16]:
# Write your code here.


LogisticRegression()

Q5: Show the intercept and coefficients of the logistic Regression

In [17]:
# Insert your code here


[4.84189529]
[[-0.03864058 -0.00032683 -0.00077313 -0.04316873]]


Recall that the logistic regression model outputs probabilities for each class. The class with the highest probability is taken as the score (prediction). 

Q6: Show the probabilities of a sample of these class probabilities for the test feature set. 

In [18]:

# Write your code here.

[[0.27862874 0.72137126]
 [0.1044124  0.8955876 ]
 [0.96211005 0.03788995]
 [0.1325443  0.8674557 ]
 [0.11508192 0.88491808]
 [0.087677   0.912323  ]
 [0.30731306 0.69268694]
 [0.33398224 0.66601776]
 [0.17883781 0.82116219]
 [0.13705047 0.86294953]
 [0.45086415 0.54913585]
 [0.06789649 0.93210351]
 [0.22090533 0.77909467]
 [0.11028334 0.88971666]
 [0.15637585 0.84362415]]


Q7: show the classes estimated by our classifier versus the actual classes from our dataset using probability threshold = 0.5.    Print predicted values and actual values

In [21]:
# Insert your code here
# Solution


[1 1 0 1 1 1 1 1 1 1 1 1 1 1 1]
7762       Low
23881      Low
30507     High
28911      Low
19484      Low
43031      Low
28188      Low
12761     High
40834      Low
27875      Low
1276       Low
22608      Low
36230      Low
13398      Low
43536      Low
Name: Output_Class, dtype: object
